### ISSUE TITLE
Second part of the assignment 8

### ISSUE THREAD

**Issue by abdcelikkanat** [bounswe/bounswe2015group7#55] opened 2015-05-07 09:07 UTC
Deadline for items 5-8: May 7th 23:59

5) Create a file called TestMathematicalOperations.java in your code repository

6) Each person should write and commit a JUnit test function containing at least 2 different fringe case tests for the function you wrote in MathematicalOperations.java (i.e. division by zero test for division). A nice tutorial can be found on http://www.vogella.com/tutorials/JUnit/article.html

7) Document the MathematicalOperations class, its member functions and test files using doxygen format.

8) Generate HTML style doxygen documentation for your groups MathematicalOperations.java. Zip and put the doxygen documentation files on your github wiki.

**Comment by fthdgn** [comment] 2015-05-07 09:34
Duplicate of issue #45 #49.

**Closed as completed by fthdgn** 2015-05-07 09:34 UTC
Labels: duplicate
